import type { HTMLAttributes } from 'react';
import { BadgeCheck, FlaskConical } from 'lucide-react';
import { cn } from '@/lib/utils';

export type DisclosureVariant = 'simulated' | 'dtdl';

const VARIANTS: Record<
  DisclosureVariant,
  { label: string; icon: typeof FlaskConical; tooltip: string; teal: boolean }
> = {
  simulated: {
    label: 'SIMULATED TELEMETRY',
    icon: FlaskConical,
    teal: false,
    tooltip:
      'All telemetry on this page is generated by the demo simulator — random-walk values within realistic per-model bounds. It is not connected to physical sensors. State history is kept for the last 60 ticks.',
  },
  dtdl: {
    label: 'DTDL v3 COMPATIBLE',
    icon: BadgeCheck,
    teal: true,
    tooltip:
      'Every twin model is a valid DTDL v3 interface (context dtmi:dtdl:context;3). View or download the JSON from any twin’s inspector.',
  },
};

export interface DisclosureChipProps extends HTMLAttributes<HTMLSpanElement> {
  variant: DisclosureVariant;
  /** Icon-only rendering (cards); the full label moves into the tooltip */
  iconOnly?: boolean;
}

/**
 * DisclosureChip — honesty-contract pill. Always visible, never hidden
 * behind a menu: `SIMULATED TELEMETRY` (slate/flask) and
 * `DTDL v3 COMPATIBLE` (teal/badge-check).
 */
export function DisclosureChip({ variant, iconOnly = false, className, ...props }: DisclosureChipProps) {
  const v = VARIANTS[variant];
  const Icon = v.icon;
  return (
    <span className={cn('group/disc relative inline-flex', className)}>
      <span
        className={cn(
          'inline-flex items-center gap-1.5 rounded-md border px-2 py-1',
          'font-mono text-[9.5px] font-medium uppercase tracking-[0.08em]',
          v.teal
            ? 'border-module-twin/30 bg-module-twin/15 text-module-twin'
            : 'border-border-hairline bg-bg-panel text-text-muted',
          iconOnly && 'px-1.5',
        )}
        {...props}
      >
        <Icon className="size-3" aria-hidden />
        {!iconOnly && v.label}
      </span>
      <span
        role="tooltip"
        className={cn(
          'pointer-events-none absolute right-0 top-full z-50 mt-2 w-60 rounded-lg',
          'border border-border-hairline bg-bg-panel-raised p-2.5 text-left font-sans text-[12px] font-normal normal-case leading-relaxed tracking-normal',
          'text-text-secondary opacity-0 shadow-xl transition-opacity duration-150 group-hover/disc:opacity-100',
        )}
      >
        <span className={cn('mb-1 block font-mono text-[9.5px] uppercase tracking-[0.08em]', v.teal ? 'text-module-twin' : 'text-text-muted')}>
          {v.label}
        </span>
        {v.tooltip}
      </span>
    </span>
  );
}
